import './lang.js'
import './time.js'
import './date.js'
import './quote.js'
import './greetingDaytime.js'
import './greetingName.js'
import './slider.js'
import './weather.js'
import './audio.js'
import './settings.js'
import './showWidgets.js'
import './images.js'
import './todo.js'
import './toggleFooterWidgets.js'

